version: '2'

services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    container_name: yii-app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  mysql:
    image: mysql:latest
    container_name: yii-mysql
    restart: always
    volumes:
      - '~/dev/dbs-data/mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_profiledata
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: yii-phpmyadmin
    links:
      - mysql:db
    ports:
      - "8081:80"